version: "3"

services:
  backend:
    image: ghcr.io/sleep2earndev/snoorefi-backend:latest
    container_name: snoorefi-backend
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
