version: "3"

services:
  backend:
    image: ghcr.io/sleep2earndev/napnad-backend:latest
    container_name: napnad-backend
    restart: always
    env_file:
      - .env
    ports:
      - "4001:4000"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
