name: Build & Push Backend to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --pull -t ghcr.io/${{ github.repository_owner }}/napnad-backend:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/napnad-backend:latest

      - name: Move Docker Compose to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.yml"
          target: "/deploy/napnad/backend"

      - name: SSH to VPS & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            if [ ! -d "/deploy/napnad/backend" ]; then
              echo "Membuat folder /deploy/napnad/backend..."
              mkdir -p /deploy/napnad/backend
            fi
            cd /deploy/napnad/backend

            # Buat atau perbarui file .env di VPS dari GitHub Secrets
            echo "${{ secrets.ENV_FILE_NAPNAD }}" > .env

            # Login ke GHCR agar bisa pull image
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Restart backend dengan image terbaru
            docker-compose pull
            docker-compose down
            docker-compose up -d --remove-orphans
            docker exec -it napnad-backend sh -c "npx prisma migrate deploy"
